<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="estilo.css">
    <title>E.E.S.T.N°1</title>
</head>
<body>
  <header>

    <h1>E.E.S.T. N°1 / Marco Silvio Ghiglione</h1>
    <img src="img/escudo.jpg" alt="Escudo de la escuela" height="90" >
    </header>
<nav>
    <ul>
      <li><a href="#">Inicio</a></li>
      <li><a href="#">Horarios</a></li>
      <li><a href="#">Novedades</a></li>
      <li><a href="#">Proyectos</a></li>
      <li><a href="#">Institucion</a></li>
      <li><a href="#">Orientaciones</a></li>
    </ul> 
</nav>      


<main>
  <section id="informacion">
    <h3>Informacion de la escuela</h3>
    <p class="titulo">El nombre de la institucion es Marco Silvio Ghiglione</p>
    <p class="titulo">La institucion se fundo en....</p> 
    <p class="titulo">Localidad de la institucion y calle + altura</p>
    <img src="" alt="(imagen de la institucion)"/>
  </section>
  <h3>Novedades</h3>
  <section id="novedades">
   
    <div class="novedad">
      <h4>titulo 1</h4>
      <h5>descripcion</h5>
    <a href="#">Ver detalles</a>
    </div>
    <div class="novedad">
      <h4>titulo 2</h4>
      <h5>descripcion</h5>
      <a href="#">Ver detalles</a>
    </div>
    <div class="novedad">
      <h4>titulo 3</h4>
      <h5>descripcion</h5>
      <a href="#">Ver detalles</a>
    </div>
  </section>

</main>



  
</body>
</html>